query getPersonasTable {
  personas {
    id
    str
    paisNacimiento
    fechaNacimiento
    genero
    estadoCivil
    telefono
    correo
    direccionDomiciliaria
  }
}

query getPersonaByIdForm($id: ID!) {
  persona(id: $id) {
    id
    tipoIdentificacion
    identificacion
    primerApellido
    segundoApellido
    primerNombre
    segundoNombre
    paisNacimiento
    fechaNacimiento
    genero
    estadoCivil
    etnia
    tipoSangre
    paisResidencia
    provinciaResidencia
    cantonResidencia
    parroquiaResidencia
    direccionDomiciliaria
    telefono
    celular
    correo
  }
  discapacidades {
    id
    nombre
    tieneDiscapacidad
    carnetConadis
    porcentajeDiscapacidad
  }
}
