query getPermisos {
  permisos {
    id
    nombre
    descripcion
  }
}

query getPermisoById($id: ID!) {
  permiso(id: $id) {
    id
    nombre
    descripcion
  }
}

query queryForUpdatePermiso($id: ID!) {
  permiso(id: $id) {
    id
    nombre
    descripcion
  }
}

query getRoles {
  grupos {
    id
    nombre
    descripcion
  }
}

query getSimple {
  permisos {
    id
    nombre
  }
}

query getByIdRol($id: ID!) {
  grupo(id: $id) {
    id
    nombre
    permisos {
      id
      nombre
    }
    descripcion
  }
}

query getByIdUpdateRol($id: ID!) {
  grupo(id: $id) {
    id
    nombre
    permisos {
      id
      nombre
    }
    permisosDisponibles {
      id
      nombre
    }
    descripcion
  }
}

query getUsuarios {
  usuarios {
    id
    username
    persona {
      id
      str
    }
  }
}

query getParametrosForm {
  personas {
    id
    str
  }

  permisos {
    id
    nombre
  }
  grupos {
    id
    nombre
  }
}

query getUsuarioById($id: ID!) {
  usuario(id: $id) {
    id
    username
    email
    permisos {
      id
      nombre
    }
    permisosDisponibles {
      id
      nombre
    }
    grupos {
      id
      nombre
    }
    gruposDisponibles {
      id
      nombre
    }
    persona {
      id
      str
    }
  }

  personas {
    id
    str
  }
}

query me {
  usuario: me {
    createdAt
    id
    username
    persona {
      id
      createdAt
      updatedAt
      authEstado
      identificacion
      tipoIdentificacion
      primerNombre
      segundoNombre
      primerApellido
      segundoApellido
      paisNacimiento
      fechaNacimiento
      genero
      estadoCivil
      tieneDiscapacidad
      discapacidades {
        id
        nombre
      }
      carnetConadis
      porcentajeDiscapacidad
      etnia
      tipoSangre
      paisResidencia
      provinciaResidencia
      cantonResidencia
      parroquiaResidencia
      direccionDomiciliaria
      sector
      telefono
      celularUno
      celularDos
      correo
      foto
      fullName
      edad
      str
      nombres
      apellidos
    }
    permisos {
      id
      nombre
    }
    grupos {
      id
      nombre
      permisos {
        id
        nombre
      }
    }
  }
}

mutation login($username: String!, $password: String!) {
  tokenAuth(username: $username, password: $password) {
    success
    token
    errors
    refreshToken
    usuario: user {
      createdAt
      id
      username
      persona {
        id
        createdAt
        updatedAt
        authEstado
        identificacion
        tipoIdentificacion
        primerNombre
        segundoNombre
        primerApellido
        segundoApellido
        paisNacimiento
        fechaNacimiento
        genero
        estadoCivil
        tieneDiscapacidad
        discapacidades {
          id
          nombre
        }
        carnetConadis
        porcentajeDiscapacidad
        etnia
        tipoSangre
        paisResidencia
        provinciaResidencia
        cantonResidencia
        parroquiaResidencia
        direccionDomiciliaria
        sector
        telefono
        celularUno
        celularDos
        correo
        foto
        fullName
        edad
        str
        nombres
        apellidos
      }
      permisos {
        id
        nombre
      }
      grupos {
        id
        nombre
        permisos {
          id
          nombre
        }
      }
    }
  }
}
