#Query usado en la pagina de crecion de matricula
query getParametrosFormMatriculaCreate {
  alumnosSinMatricula {
    id
    personaStr
  }
  aulas: aulasPeriodoAbierto {
    id
    nombre
  }
}
#Query para carga inicial del form de Matricula
query getMatriculaByIdFormUpdate($id: ID!) {
  matricula(id: $id) {
    id
    tratamiento
    matricula
    numeroMatricula
    aporteVoluntario
    diagnosticoClinico
    diagnosticoFinal
    aula {
      id
      nombre
    }
    infoAula: aula {
      periodo {
        id
        estado
      }
    }
    alumno {
      id
      personaStr
    }
  }
  aulas {
    id
    nombre
  }
}

query getMatriculaByIdDetail($id: ID!) {
  matricula(id: $id) {
    id
    tratamiento
    matricula
    numeroMatricula
    aporteVoluntario
    diagnosticoClinico
    aula {
      id
      nombre
      grado
    }
    alumno {
      id
      persona {
        id
        identificacion
        nombres
        apellidos
        fechaNacimiento
        edad
        carnetConadis
        direccionDomiciliaria
        telefono
        celularUno
        correo
        provinciaResidencia
        cantonResidencia
        parroquiaResidencia
      }
      padre {
        identificacion
        fullName
        ocupacion
        direccion
        telefono
        celular
      }
      madre {
        identificacion
        fullName
        ocupacion
        direccion
        telefono
        celular
      }
    }
  }
}

query getMatriculasTable {
  matriculas {
    id

    numeroMatricula
    aporteVoluntario
    estadoMatricula

    aula {
      id
      nombre
      periodo {
        nombre
      }
    }

    alumno {
      id
      personaStr
    }
  }
}

query getAulasTable {
  aulas {
    id
    nombre
    capacidad
    grado
    docentes {
      id
      persona {
        id
        str
      }
    }
    periodo {
      id
      nombre
      estado
    }
  }
}

query getAulaByIdDetail($id: ID!) {
  aula(id: $id) {
    id
    nombre
    capacidad
    grado
    periodo {
      id
      nombre
    }
    docentes {
      id
      personaStr
    }
    alumnos {
      id
      personaStr
    }
  }
}

query getParametrosFormAula {
  periodosLectivos(estados: [ABIERTO]) {
    id
    nombre
  }

  personalByFunciones(funciones: ["DOCENTE"]) {
    id
    personaStr
  }
}
query getAulaByIdForm($id: ID!) {
  aula(id: $id) {
    id
    nombre
    periodo {
      id
      nombre
    }
    docentes {
      id
      personaStr
    }
    grado
    capacidad
    infoPeriodo: periodo {
      id
      nombre
      estado
    }
  }

  periodosLectivos {
    id
    nombre
  }

  personalByFunciones(funciones: ["DOCENTE"]) {
    id
    personaStr
  }
}
query getByIdMateria($id: ID!) {
  materia(id: $id) {
    id
    nombre
    codigo
    grado
    horasPresencial
    descripcion
    objetivo
    objetivoEspecifico
  }
}

query getAllMateria {
  materias {
    id
    nombre
    codigo
    grado
    horasPresencial
    descripcion
    objetivo
    objetivoEspecifico
  }
}
query getParametrosFormPeriodos {
  personalAll {
    id
    personaStr
  }
}
query getByIdPeriodo($id: ID!) {
  periodoLectivo(id: $id) {
    id
    nombre
    fechaInicio
    fechaFin
    fechaFinClases
    estado
    observaciones
    coordinador {
      id
      personaStr
    }
    subCoordinador {
      id
      personaStr
    }
    director {
      id
      personaStr
    }
  }
  personalAll {
    id
    personaStr
  }
}
query getPeriodoLectivoByIdDetail($id: ID!) {
  periodoLectivo(id: $id) {
    id
    nombre
    fechaInicio
    fechaFin
    fechaFinClases
    estado
    observaciones
    totalMatriculas: numeroMatriculas
    matriculasCreadas: numeroMatriculas(estados: [CREADA])
    matriculasFinalizadas: numeroMatriculas(estados: [FINALIZADA])
    matriculasAnuladas: numeroMatriculas(estados: [ANULADA])
    habilitarCierre
    coordinador {
      id
      personaStr
    }
    subCoordinador {
      id
      personaStr
    }
    director {
      id
      personaStr
    }
  }
}

query getPeriodosTable {
  periodosLectivos {
    id
    nombre
    fechaInicio
    fechaFin
    fechaFinClases
    estado
    coordinador {
      personaStr
    }
    subCoordinador {
      personaStr
    }
    director {
      personaStr
    }
  }
}
