mutation createPersona($input: CreatePersonaInput!) {
  createPersona(input: $input) {
    persona {
      id
      createdAt
    }
  }
}

mutation updatePersona($id: ID!, $input: UpdatePersonaInput!) {
  updatePersona(id: $id, input: $input) {
    persona {
      id
      createdAt
      updatedAt
    }
  }
}

mutation deletePersona($id: ID!) {
  deletePersona(id: $id) {
    found
    deletedId
  }
}

mutation createPersonal($input: CreatePersonalInput!) {
  createPersonal(input: $input) {
    personal {
      id
      createdAt
    }
  }
}

mutation updatePersonal($id: ID!, $input: UpdatePersonalInput!) {
  updatePersonal(id: $id, input: $input) {
    personal {
      id
      createdAt
    }
  }
}

mutation deletePersonal($id: ID!) {
  deletePersonal(id: $id) {
    deletedId
    found
  }
}

mutation createAlumno($input: CreateAlumnoInput!) {
  createAlumno(input: $input) {
    alumno {
      id
      createdAt
    }
  }
}

mutation updateAlumno($id: ID!, $input: UpdateAlumnoInput!) {
  updateAlumno(id: $id, input: $input) {
    alumno {
      id
      createdAt
    }
  }
}

mutation deleteAlumno($id: ID!) {
  deleteAlumno(id: $id) {
    found
    deletedId
  }
}

mutation createDiscapacidad($input: CreateDiscapacidadInput!) {
  createDiscapacidad(input: $input) {
    discapacidad {
      id
      createdAt
    }
  }
}

mutation deleteDiscapacidad($id: ID!) {
  deleteDiscapacidad(id: $id) {
    found
    deletedId
  }
}

mutation updateDiscapacidad($id: ID!, $input: UpdateDiscapacidadInput!) {
  updateDiscapacidad(input: $input, id: $id) {
    discapacidad {
      id
      createdAt
    }
  }
}
