query getParametrosFormMatriculas {
  alumnos {
    id
    personaStr
  }
}


query getMatriculaById($id: ID!) {
  matricula(id: $id) {
    id
    tratamiento
    diagnostico
    matricula
    numeroMatricula
    aporteVoluntario
    diagnosticoFinal
    aula {
      id
      nombre
    }
    alumno {
      id
      persona {
        id
        str
      }
    }
  }

  aulas {
    id
    nombre
  }
  alumnos {
    id
    persona {
      id
      str
    }
  }
}

query getMatriculas {
  matriculas {
    id
    aula {
      id
      nombre
    }

    alumno {
      id
      persona {
        id
        str
      }
    }
  }
}

query getAll {
  aulas {
    id
    nombre
    capacidad
    grado
    docentes {
      id
      persona {
        id
        str
      }
    }
    periodo {
      id
      nombre
    }
  }
}

query getAulaById($id: ID!) {
  aula(id: $id) {
    id
    nombre
    periodo {
      id
      nombre
    }
    docentes {
      id
      persona {
        id
        str
      }
    }
    grado
    capacidad
  }
}

query getParametrosFormAula {
  periodosLectivos {
    id
    nombre
  }

  personalByFunciones(funciones: ["DOCENTE"]) {
    id
    personaStr
  }
}
query getAulaByIdForm($id: ID!) {
  aula(id: $id) {
    id
    nombre
    periodo {
      id
      nombre
    }
    docentes {
      id
      personaStr
    }
    grado
    capacidad
  }

  periodosLectivos {
    id
    nombre
  }

  personalByFunciones(funciones: ["DOCENTE"]) {
    id
    personaStr
  }
}
query getByIdMateria($id: ID!) {
  materia(id: $id) {
    id
    nombre
    codigo
    grado
    horasPresencial
    descripcion
    objetivo
    objetivoEspecifico
  }
}

query getAllMateria {
  materias {
    id
    nombre
    codigo
    grado
    horasPresencial
    descripcion
    objetivo
    objetivoEspecifico
  }
}

query getByIdPeriodo($id: ID!) {
  periodoLectivo(id: $id) {
    id
    nombre
    fechaInicio
    fechaFin
    fechaFinClases
    estado
    observaciones
  }
}

query getAllPeriodo {
  periodosLectivos {
    id
    nombre
    fechaInicio
    fechaFin
    fechaFinClases
    estado
  }
}
